### ISSUE TITLE
[Crash] Vampire Bite -> BackstabbingEnchantment NoClassDefFoundError 

### ISSUE THREAD

**Issue by lunofe** [TheGridExpert/VampiresDelight#4]
When applying the _Vampire Bite_ enchantment to a vampire sword, the game crashes because [Vampirism.co's Farmer's Bliss](https://github.com/lunofe/FarmersBliss/commit/2a4d0c115cfe7db9b6edcb3c8f34d0fcb898d27a) does not feature the _Backstabbing_ enchantment which is expected to exist by Vampire's Delight.

[Screencast from 2024-04-01 20-42-54.webm](https://github.com/TheGridExpert/VampiresDelight/assets/42828197/2f1b8b85-5ffd-4b12-9ea5-2047c4e8077a)

```ls
Description: mouseClicked event handler

java.lang.NoClassDefFoundError: vectorwing/farmersdelight/common/item/enchantment/BackstabbingEnchantment
	at net.minecraft.world.item.enchantment.Enchantment.handler$bdb000$canBackstabbingBeApplied(Enchantment.java:516) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,re:classloading,pl:mixin:APP:vampiresdelight.mixins.json:MixinEnchantment,pl:mixin:A}
	at net.minecraft.world.item.enchantment.Enchantment.m_6081_(Enchantment.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,re:classloading,pl:mixin:APP:vampiresdelight.mixins.json:MixinEnchantment,pl:mixin:A}
	at net.minecraft.world.inventory.AnvilMenu.m_6640_(AnvilMenu.java:177) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.inventory.ItemCombinerMenu.m_6199_(ItemCombinerMenu.java:106) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.inventory.ItemCombinerMenu$3.m_6596_(ItemCombinerMenu.java:96) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:classloading}
	at net.minecraft.world.SimpleContainer.m_6836_(SimpleContainer.java:144) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:classloading}
	at net.minecraft.world.inventory.Slot.m_5852_(Slot.java:63) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:classloading}
	at net.minecraft.world.inventory.Slot.m_269060_(Slot.java:59) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:classloading}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_38903_(AbstractContainerMenu.java:660) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.inventory.ItemCombinerMenu.m_7648_(ItemCombinerMenu.java:147) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:394) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:294) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_171799_(MultiPlayerGameMode.java:431) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6597_(AbstractContainerScreen.java:536) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_6375_(AbstractContainerScreen.java:329) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:92) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:konkrete.mixin.json:MixinMouseHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:konkrete.mixin.json:IMixinScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:konkrete.mixin.json:MixinMouseHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:konkrete.mixin.json:MixinMouseHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:188) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:konkrete.mixin.json:MixinMouseHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%2374!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%2386!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar%2374!/:build 7] {re:mixin}
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.json:MixinGlStateManager,pl:mixin:APP:mixins.oculus.json:MixinRenderSystem,pl:mixin:APP:mixins.oculus.json:statelisteners.MixinRenderSystem,pl:mixin:APP:embeddium.mixins.json:workarounds.event_loop.RenderSystemMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1173) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[minecraft-1.20.1-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.17.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[?:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?] {}
Caused by: java.lang.ClassNotFoundException: vectorwing.farmersdelight.common.item.enchantment.BackstabbingEnchantment
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	... 51 more
```

**Comment by TheGridExpert** [comment]
Thank you for reporting it :). Fixed it in https://github.com/TheGridExpert/VampiresDelight/commit/1f89afd56e42558232dbcdeae96b681c660aa124

**Comment by TheGridExpert** [comment]
Thank you for reporting it :). Fixed it in https://github.com/TheGridExpert/VampiresDelight/commit/1f89afd56e42558232dbcdeae96b681c660aa124
